version: 2
jobs:
  test-packages:
    docker:
      - image: circleci/node:12.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "yarn.lock" }}
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "yarn.lock" }}
          paths:
            - ~/.cache

      # TODO: run these in parallel
      - run:
          name: election-manager
          command: |
            yarn --cwd apps/election-manager test:coverage
      - run:
          name: hmpb-ui
          command: |
            yarn --cwd libs/hmpb-ui test:coverage

workflows:
  version: 2
  test-packages:
    jobs:
      - test-packages
